spring:
  application:
    name: printscript-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/printdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
server:
  port: 8082